### GET all contacts
GET http://localhost:3000/contacts
Content-Type: application/json

###

### GET contact by ID
GET http://localhost:3000/contacts/67cc9c114d9bc9cf4671dec0
Content-Type: application/json

###

### POST create a new contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe", 
  "email": "johndoe@example.com",
  "favoriteColor": "Blue",
  "birthday": "1990-01-01"
}

###

### PUT update a contact
PUT http://localhost:3000/contacts/67cc9c114d9bc9cf4671dec0
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Smith",
  "email": "jane.smith@example.com",
  "favoriteColor": "Red",
  "birthday": "1985-05-05"
}

###

### DELETE contact
DELETE http://localhost:3000/contacts/67cc9c114d9bc9cf4671dec0
Content-Type: application/json